"""Legacy compatibility exports for config-driven CLI workflows."""

from __future__ import annotations

from alphaforge.cli.artifacts import (
    write_artifact_bundle,
    write_dataframe,
    write_indexed_artifact_bundle,
    write_json,
)
from alphaforge.cli.charts import (
    write_compare_chart_bundle,
    write_report_chart_bundle_from_context,
)
from alphaforge.cli.comparison import (
    build_compare_artifact_metadata,
    build_compare_runs_report,
    compare_indexed_runs,
    format_run_index_table,
    list_indexed_runs,
    rank_compare_runs,
    write_compare_artifact_bundle,
)
from alphaforge.cli.data_loading import (
    dataset_requires_benchmark_returns as _dataset_requires_benchmark_returns,
    dataset_requires_fundamentals as _dataset_requires_fundamentals,
    dataset_requires_memberships as _dataset_requires_memberships,
    dataset_requires_shares_outstanding as _dataset_requires_shares_outstanding,
    dataset_requires_trading_status as _dataset_requires_trading_status,
    load_benchmark_returns_from_config,
    load_borrow_availability_from_config,
    load_classifications_from_config,
    load_corporate_actions_from_config,
    load_fundamentals_from_config,
    load_market_data_from_config,
    load_memberships_from_config,
    load_shares_outstanding_from_config,
    load_symbol_metadata_from_config,
    load_trading_calendar_from_config,
    load_trading_status_from_config,
)
from alphaforge.cli.errors import WorkflowError
from alphaforge.cli.pipeline import (
    add_signal_from_config,
    build_dataset_from_config,
    build_dataset_from_market_data,
    build_weights_from_config,
    require_signal_config,
    run_backtest_from_config,
    run_backtest_with_config as _run_backtest_with_config,
)
from alphaforge.cli.report_context import (
    build_report_context,
    build_report_context as _build_report_context,
    validate_diagnostics_column as _validate_diagnostics_column,
)
from alphaforge.cli.report_package import (
    build_report_package,
    build_report_text,
    write_report_artifact_bundle,
    write_report_chart_bundle,
)
from alphaforge.cli.research_metadata import (
    build_config_snapshot as _build_config_snapshot,
    build_dataset_feature_metadata_from_config as _build_dataset_feature_metadata_from_config,
    build_research_context_metadata,
    build_research_metadata_from_config as _build_research_metadata_from_config,
    build_signal_pipeline_metadata_from_config as _build_signal_pipeline_metadata_from_config,
    dataframe_records as _dataframe_records,
    scalar_or_none as _scalar_or_none,
    series_to_metadata_dict as _series_to_metadata_dict,
)
from alphaforge.cli.parameter_sweep import (
    build_sweep_artifact_metadata,
    normalize_sweep_values as _normalize_sweep_values,
    replace_signal_parameter as _replace_signal_parameter,
    run_signal_parameter_sweep,
)
from alphaforge.cli.reports import (
    _describe_signal_transform,
    _format_number_or_nan,
    _format_percent_or_nan,
    describe_benchmark_configuration,
    describe_benchmark_data,
    describe_borrow_availability_configuration,
    describe_borrow_availability_data,
    describe_classifications_configuration,
    describe_classifications_data,
    describe_corporate_actions_configuration,
    describe_corporate_actions_data,
    describe_data_quality,
    describe_diagnostics_overview,
    describe_execution_configuration,
    describe_execution_results,
    describe_fundamentals_configuration,
    describe_fundamentals_data,
    describe_market_data,
    describe_memberships_configuration,
    describe_memberships_data,
    describe_portfolio_constraints,
    describe_research_workflow,
    describe_shares_outstanding_configuration,
    describe_shares_outstanding_data,
    describe_symbol_metadata_configuration,
    describe_symbol_metadata_data,
    describe_trading_calendar_configuration,
    describe_trading_calendar_data,
    describe_trading_status_configuration,
    describe_trading_status_data,
    describe_universe_configuration,
    describe_universe_eligibility,
    build_report_metadata,
    render_report_text,
    write_report_html_page,
)
from alphaforge.cli.validation import normalize_positive_int
from alphaforge.cli.validation_report import build_validate_data_text
from alphaforge.cli.walk_forward import (
    build_walk_forward_artifact_metadata_from_config as build_walk_forward_artifact_metadata,
    build_walk_forward_folds,
    evaluate_walk_forward_slice,
    extract_unique_dates,
    extract_walk_forward_selection_score,
    normalize_walk_forward_selection_metric,
    run_walk_forward_parameter_selection,
)

__all__ = [
    "WorkflowError",
    "add_signal_from_config",
    "build_compare_artifact_metadata",
    "build_compare_runs_report",
    "build_dataset_from_config",
    "build_dataset_from_market_data",
    "build_report_context",
    "build_report_metadata",
    "build_report_package",
    "build_report_text",
    "build_research_context_metadata",
    "build_sweep_artifact_metadata",
    "build_validate_data_text",
    "build_walk_forward_artifact_metadata",
    "build_walk_forward_folds",
    "build_weights_from_config",
    "compare_indexed_runs",
    "describe_benchmark_configuration",
    "describe_benchmark_data",
    "describe_borrow_availability_configuration",
    "describe_borrow_availability_data",
    "describe_classifications_configuration",
    "describe_classifications_data",
    "describe_corporate_actions_configuration",
    "describe_corporate_actions_data",
    "describe_data_quality",
    "describe_diagnostics_overview",
    "describe_execution_configuration",
    "describe_execution_results",
    "describe_fundamentals_configuration",
    "describe_fundamentals_data",
    "describe_market_data",
    "describe_memberships_configuration",
    "describe_memberships_data",
    "describe_portfolio_constraints",
    "describe_research_workflow",
    "describe_shares_outstanding_configuration",
    "describe_shares_outstanding_data",
    "describe_symbol_metadata_configuration",
    "describe_symbol_metadata_data",
    "describe_trading_calendar_configuration",
    "describe_trading_calendar_data",
    "describe_trading_status_configuration",
    "describe_trading_status_data",
    "describe_universe_configuration",
    "describe_universe_eligibility",
    "evaluate_walk_forward_slice",
    "extract_unique_dates",
    "extract_walk_forward_selection_score",
    "format_run_index_table",
    "list_indexed_runs",
    "load_benchmark_returns_from_config",
    "load_borrow_availability_from_config",
    "load_classifications_from_config",
    "load_corporate_actions_from_config",
    "load_fundamentals_from_config",
    "load_market_data_from_config",
    "load_memberships_from_config",
    "load_shares_outstanding_from_config",
    "load_symbol_metadata_from_config",
    "load_trading_calendar_from_config",
    "load_trading_status_from_config",
    "normalize_positive_int",
    "normalize_walk_forward_selection_metric",
    "rank_compare_runs",
    "render_report_text",
    "require_signal_config",
    "run_backtest_from_config",
    "run_signal_parameter_sweep",
    "run_walk_forward_parameter_selection",
    "write_artifact_bundle",
    "write_compare_artifact_bundle",
    "write_compare_chart_bundle",
    "write_dataframe",
    "write_indexed_artifact_bundle",
    "write_json",
    "write_report_artifact_bundle",
    "write_report_chart_bundle",
    "write_report_chart_bundle_from_context",
    "write_report_html_page",
]
