"""Analytics utilities for AlphaForge."""

from alphaforge.analytics.factor_diagnostics import (
    FactorDiagnosticsError,
    compute_grouped_ic_series,
    compute_ic_decay_series,
    compute_ic_decay_summary,
    compute_ic_series,
    compute_quantile_bucket_returns,
    compute_quantile_spread_series,
    compute_rolling_ic_series,
    compute_signal_coverage_by_date,
    summarize_ic,
    summarize_grouped_ic,
    summarize_rolling_ic,
    summarize_signal_coverage,
)
from alphaforge.analytics.parameter_sweep import (
    ParameterSweepError,
    format_parameter_sweep_results,
    validate_parameter_sweep_results,
)
from alphaforge.analytics.performance import (
    AnalyticsError,
    compute_drawdown_series,
    format_performance_summary,
    format_relative_performance_summary,
    summarize_backtest,
    summarize_relative_performance,
)
from alphaforge.analytics.walk_forward import (
    WalkForwardError,
    format_walk_forward_report,
    validate_walk_forward_results,
)
from alphaforge.analytics.visualization import (
    save_compare_summary_chart,
    VisualizationError,
    save_coverage_summary_chart,
    save_coverage_timeseries_chart,
    save_drawdown_chart,
    save_exposure_turnover_chart,
    save_ic_cumulative_chart,
    save_ic_decay_chart,
    save_ic_series_chart,
    save_nav_overview_chart,
    save_quantile_bucket_chart,
    save_quantile_spread_chart,
    save_rolling_benchmark_risk_chart,
)

__all__ = [
    "AnalyticsError",
    "FactorDiagnosticsError",
    "ParameterSweepError",
    "VisualizationError",
    "WalkForwardError",
    "compute_grouped_ic_series",
    "compute_ic_decay_series",
    "compute_ic_decay_summary",
    "compute_ic_series",
    "compute_quantile_bucket_returns",
    "compute_quantile_spread_series",
    "compute_rolling_ic_series",
    "compute_signal_coverage_by_date",
    "compute_drawdown_series",
    "format_parameter_sweep_results",
    "format_performance_summary",
    "format_relative_performance_summary",
    "format_walk_forward_report",
    "save_compare_summary_chart",
    "summarize_ic",
    "summarize_grouped_ic",
    "summarize_rolling_ic",
    "summarize_backtest",
    "summarize_relative_performance",
    "summarize_signal_coverage",
    "save_coverage_summary_chart",
    "save_coverage_timeseries_chart",
    "save_drawdown_chart",
    "save_exposure_turnover_chart",
    "save_ic_cumulative_chart",
    "save_ic_decay_chart",
    "save_ic_series_chart",
    "save_nav_overview_chart",
    "save_quantile_bucket_chart",
    "save_quantile_spread_chart",
    "save_rolling_benchmark_risk_chart",
    "validate_parameter_sweep_results",
    "validate_walk_forward_results",
]
